owner: darwinbaysa06
repo: status

sites:
  - name: "[Website] Main Website (dp)"
    url: https://dpG06.top
    slug: web-dp
  - name: "[Website] Personal Website (Darwin)"
    url: https://darwinbaysa06.dpG06.top
    slug: web-darwin
  - name: "[Service] Link Shortener Service"
    url: https://go.dpg06.top
    slug: svc-link-shortener
  - name: "[Service] Status Monitoring"
    url: https://status.dpG06.top
    slug: svc-status-monitor
  - name: "[Service] Code Snippets (Fastbin)"
    url: https://codesnips.dpg06.top/
    slug: svc-code-snippets
  - name: "[Service] Project Distribution Service"
    url: https://dist.dpg06.top
    slug: svc-r2-dist
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: "[Service] Personal Files Service"
    url: $SITESEC_SVC_R2_PERSONAL
    expectedStatusCodes:
      - 200
      - 201
      - 404
    slug: svc-r2-personal
  - name: "[Service] School Projects Distribution Service"
    url: $SITESEC_SVC_R2_SCHOOL
    expectedStatusCodes:
      - 200
      - 201
      - 404
    slug: svc-r2-school
  - name: "[Service] Repolist - Private Projects Frontent Service"
    url: $SITESEC_SVC_PRIVATEREPOFRONT
    slug: svc-repolist
  - name: "[Project] SSStation Service"
    url: https://ssstation.dpg06.top
    slug: proj-ssstation

status-website:
  cname: status.dpG06.top
  logoUrl: https://raw.githubusercontent.com/darwinbaysa06/asset-library/refs/heads/main/services/statusMonitor.png
  name: dp Services Status Monitoring
  introTitle: "dp Services Status"
  navbar:
    - title: Contact
      href: https://dpG06.top/info
    - title: Web
      href: https://dpG06.top

i18n:
  footer: "Copyright 2021-2026 by dp. Powered by [Upptime](https://github.com/upptime/upptime)"
