owner: dplayz
repo: status

sites:
  - name: Main Website Service
    url: https://dpG06.top
  - name: Static Link Service
    url: https://l.dpg06.top
  - name: Dynamic Link Service
    url: https://lv2.dpg06.top
  - name: Hidden Blog Service
    url: $URL_SKLBLOG
  - name: Status Service
    url: https://status.dpG06.top
# - name: File Service
#   url: https://files.dplayzgames06.tk
  - name: Workstation Service
    url: https://workstation.dpG06.top
  - name: Fastbin Service
    url: https://paste.dpG06.top


status-website:
  cname: status.dplayzgames06.tk
  logoUrl: https://raw.githubusercontent.com/dplayz/status/master/assets/statussvclogo.png
  name: dplayz Games Services Status
  introTitle: "dplayz Games Service Status"
  navbar:
    - title: Info
      href: https://dplayzgames06.tk/info
    - title: Main Website
      href: https://dplayzgames06.tk
    - title: Workstation
      href: https://workstation.dplayzgames06.tk
i18n:
  footer: "Copyright 2021-2023 by dplayz Games. Powered by [Upptime](https://github.com/upptime/upptime)"
