owner: dplayz
repo: status

sites:
  - name: Main Website Service
    url: https://dpG06.top
  - name: Static Link Service
    url: https://go.dpg06.top
  - name: Status Service
    url: https://status.dpG06.top
# - name: File Service
#   url: https://files.dplayzgames06.tk
# - name: Workstation Service
#   url: https://workstation.dpG06.top
  - name: Fastbin Service
    url: https://snippets.dpG06.top


status-website:
  cname: status.dpG06.top
  logoUrl: https://raw.githubusercontent.com/dplayz/status/master/assets/statussvclogo.png
  name: dp Services Status
  introTitle: "dp Services Status"
  navbar:
    - title: Info
      href: https://dpG06.top/info
    - title: Main Website
      href: https://dpG06.top
#    - title: Workstation
#      href: https://workstation.dpG06.top
i18n:
  footer: "Copyright 2021-2024 by dplayz Games. Powered by [Upptime](https://github.com/upptime/upptime)"
