owner: dplayz
repo: status

sites:
  - name: Main Website Service
    url: https://dpG06.top
  - name: Link Service
    url: https://go.dpg06.top
  - name: Status Service
    url: https://status.dpG06.top
  - name: Fastbin Service
    url: https://code-snippets.dpG06.top


status-website:
  cname: status.dpG06.top
  logoUrl: https://raw.githubusercontent.com/dplayz/status/master/assets/statussvclogo.png
  name: dp Services Status
  introTitle: "dp Services Status"
  navbar:
    - title: About
      href: https://dpG06.top/info
    - title: Main Website
      href: https://dpG06.top
#    - title: Workstation
#      href: https://workstation.dpG06.top
i18n:
  footer: "Copyright 2021-2025 by dp. Powered by [Upptime](https://github.com/upptime/upptime)"
