owner: dplayz
repo: status

sites:
  - name: Main Website Service
    url: https://dplayzgames06.tk
  - name: Static Link Service
    url: https://diipii.tk
  - name: Dynamic Link Service
    url: https://lnksvc2.diipii.tk
  - name: Hidden Blog Service
    url: $URL_SKLBLOG
  - name: Status Service
    url: https://status.dplayzgames06.tk
  - name: File Service
    url: https://files.dplayzgames06.tk
  - name: Workstation Service
    url: https://workstation.dplayzgames06.tk


status-website:
  cname: status.dplayzgames06.tk
  logoUrl: /statussvclogo.png
  name: dplayz Games Services Status
  introTitle: "dplayz Games Service Status"
  navbar:
    - title: Info
      href: https://dplayzgames06.tk/info
    - title: Main Website
      href: https://dplayzgames06.tk
    - title: Workstation
      href: https://workstation.dplayzgames06.tk
i18n:
  footer: "Copyright 2021-2023 by dplayz Games. Powered by [Upptime](https://github.com/upptime/upptime)"
